# Generated by Django 5.2.6 on 2025-10-06 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='abertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='duracao',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=20),
        ),
    ]
