# Generated by Django 5.2.6 on 2025-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0002_chamado_data_alter_chamado_abertura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=100)),
                ('regional', models.CharField(max_length=100)),
                ('lider', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
