# Generated by Django 5.2.6 on 2025-10-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_alter_chamado_usuario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventarioexcel',
            table='chamados_inventarioexcel',
        ),
    ]
