# Generated by Django 5.2.6 on 2025-10-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_inventarioexcel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='outro_motivo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
