# Generated by Django 5.2.6 on 2025-10-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0007_chatmessage'),
    ]

    operations = [
    ]
