# Generated by Django 5.2.6 on 2025-10-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0008_auto_20251017_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='papel',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('usuario', 'Usuário')], default='usuario', max_length=10),
        ),
    ]
