# Generated by Django 5.2.6 on 2025-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_alter_customuser_papel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='duracao_manual',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
