# Generated by Django 5.2.6 on 2025-10-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_chamado_duracao_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='duracao_manual',
            new_name='tempo_manual',
        ),
    ]
