# Generated by Django 5.2.6 on 2025-10-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_rename_duracao_manual_chamado_tempo_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, help_text='+5511975065259', max_length=15, null=True),
        ),
    ]
