# Generated by Django 5.2.6 on 2025-11-12 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_alter_customuser_telefone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-aberto_em'], 'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='abertura',
            new_name='aberto_em',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='fechamento',
            new_name='fechado_em',
        ),
        migrations.RemoveField(
            model_name='chamado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='chamado',
            name='aberto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_abertos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chamado',
            name='fechado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_fechados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateField(blank=True, help_text='Data de referência (legado)', null=True),
        ),
    ]
