# Generated by Django 5.2.6 on 2025-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0014_alter_chamado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
